<?php
/**
 * ══════════════════════════════════════════════════════════════════════════════
 * auth.php — Centralized Session Security & Authorization Middleware
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * Architecture & Purpose:
 *   This file provides the primary security perimeter for the entire NPC LMS.
 *   It guarantees role isolation, live database permission synchronization,
 *   session hardening, idle and absolute timeout verification, and cross-portal
 *   access guards for all endpoints.
 *
 * Key Capabilities:
 *   1. Hardened Session Settings: Enforces HttpOnly, SameSite, Strict Mode, and Secure cookies.
 *   2. Real-Time Account & Role Sync: Checks the MySQL database on EVERY page load/refresh
 *      to ensure that administrative changes (role promotions/demotions, bans, section updates)
 *      take effect immediately across all user devices without requiring manual re-login.
 *   3. Strict Portal Access Guards (`require_admin`, `require_teacher`, `require_student_area`):
 *      Prevents unauthorized cross-role tampering and immediately redirects unauthorized visitors
 *      back to their own dedicated portal.
 *   4. Clean JSON API Error Handling: Gracefully emits HTTP 401/403 JSON envelopes for REST requests.
 */

require_once __DIR__ . '/supabase_helper.php';

// ─── 1. Hardened Session Initialization ────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    // Prevent JavaScript cookie theft (XSS mitigation)
    ini_set('session.cookie_httponly', '1');
    // Prevent Cross-Site Request Forgery via third-party contexts
    ini_set('session.cookie_samesite', 'Lax');
    // Reject uninitialized/unrecognized session IDs generated by attackers
    ini_set('session.use_strict_mode', '1');
    // Mandate cookies only, disallowing session IDs passed in query strings
    ini_set('session.use_only_cookies', '1');

    // Enable TLS/HTTPS cookie encryption when serving over SSL or behind SSL-terminating proxies
    if ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) {
        ini_set('session.cookie_secure', '1');
    }

    session_start();
}

// ─── 2. Session Lifetime & Inactivity Constants ────────────────────────────────
define('SESSION_MAX_LIFETIME', 8 * 60 * 60);  // 8 hours absolute maximum lifespan
define('SESSION_IDLE_TIMEOUT', 2 * 60 * 60);  // 2 hours maximum inactivity threshold

/**
 * Function: isSessionValid
 *
 * Comprehensively validates the current PHP session against both temporal limits
 * and live MySQL database records.
 *
 * Detailed Lifecycle Operations:
 *   Step 1: Confirms the presence of an active `user_id`.
 *   Step 2: Enforces absolute maximum lifespan (8 hours). Destroys session if expired.
 *   Step 3: Enforces idle timeout (2 hours of inactivity). Destroys session if idle.
 *   Step 4: Real-Time MySQL Synchronization:
 *           - Queries the `users` table using the user's primary key or email.
 *           - If the user record was deleted by an admin, terminates the session.
 *           - If the user account is flagged as Banned, Restricted, Snoozed, or Inactive,
 *             immediately terminates session to lock them out on all devices.
 *           - Synchronizes roles: If the admin modified the user's role from Admin to Faculty,
 *             updates `$_SESSION['role']`, `$_SESSION['base_role']`, and `$_SESSION['active_portal']`
 *             so that refreshing the browser stays locked to their new role.
 *           - For students, synchronizes their current Section, Program, and Scholar Status.
 *   Step 5: Updates the `last_activity` timestamp to the current timestamp.
 *
 * @return bool Returns true if the session is authenticated, active, and authorized; false otherwise.
 */
function isSessionValid(): bool {
    if (!isset($_SESSION['user_id'])) {
        return false;
    }

    $now = time();

    // Initialize timestamps if missing (legacy session fallback)
    if (!isset($_SESSION['login_time'])) {
        $_SESSION['login_time'] = $now;
        $_SESSION['last_activity'] = $now;
    }

    // Check absolute session lifetime (exceeding 8 hours requires fresh authentication)
    if (($now - $_SESSION['login_time']) > SESSION_MAX_LIFETIME) {
        destroySession();
        return false;
    }

    // Check idle inactivity timeout (exceeding 2 hours without navigation)
    if (isset($_SESSION['last_activity']) && ($now - $_SESSION['last_activity']) > SESSION_IDLE_TIMEOUT) {
        destroySession();
        return false;
    }

    // ─── Real-Time Database State Verification ─────────────────────────────────
    try {
        $db = getDB();
        $uStmt = $db->prepare("SELECT id, email, full_name, role, program, section, is_active, status, student_number FROM users WHERE id = ? OR LOWER(email) = ? LIMIT 1");
        $uStmt->execute([$_SESSION['user_id'], strtolower($_SESSION['email'] ?? '')]);
        $liveUser = $uStmt->fetch(PDO::FETCH_ASSOC);

        if (!$liveUser) {
            // Account was deleted by system administrator; evict immediately
            destroySession();
            return false;
        }

        // Align internal user ID in case of ID alias resolution
        if (!empty($liveUser['id']) && ($_SESSION['user_id'] ?? '') !== $liveUser['id']) {
            $_SESSION['user_id'] = $liveUser['id'];
        }

        $userStatus = $liveUser['status'] ?? ($liveUser['is_active'] ? 'Active' : 'Inactive');
        $isActive = (int)($liveUser['is_active'] ?? 1);

        // Security Lockdown: Evict accounts that are Banned, Restricted, Snoozed, or Inactive
        if ($userStatus === 'Banned' || $userStatus === 'Restricted' || $userStatus === 'Snoozed' || $isActive === 0) {
            destroySession();
            return false;
        }

        // Real-Time Role Synchronization: Live database record is the authoritative source of truth
        $newRole = $liveUser['role'] ?? 'student';
        if ($newRole === 'faculty') {
            $newRole = 'teacher';
        }
        $currentRole = $_SESSION['role'] ?? 'student';
        $currentBaseRole = $_SESSION['base_role'] ?? $currentRole;

        // Synchronize session roles if database was changed or if role disparity is detected
        if ($currentBaseRole !== $newRole || ($newRole !== 'admin' && $newRole !== 'registrar' && $currentRole !== $newRole)) {
            $_SESSION['base_role'] = $newRole;
            $_SESSION['role'] = $newRole;
            $_SESSION['active_portal'] = in_array($newRole, ['admin', 'registrar']) ? 'admin' : ($newRole === 'teacher' ? 'faculty' : 'student');
        }

        // Real-Time Program & Section Synchronization
        $newProg = $liveUser['program'] ?? '';
        $newSec = $liveUser['section'] ?? '';

        if ($newRole === 'student') {
            $stdStmt = $db->prepare("SELECT program, section, student_number, scholar_status FROM students WHERE user_id = ? OR LOWER(email) = ? LIMIT 1");
            $stdStmt->execute([$liveUser['id'], strtolower($liveUser['email'])]);
            $stdRow = $stdStmt->fetch(PDO::FETCH_ASSOC);
            if ($stdRow) {
                if (!empty($stdRow['program'])) $newProg = $stdRow['program'];
                if (!empty($stdRow['section'])) $newSec = $stdRow['section'];
                if (!empty($stdRow['student_number'])) $_SESSION['student_number'] = $stdRow['student_number'];
                if (!empty($stdRow['scholar_status'])) $_SESSION['scholar_status'] = $stdRow['scholar_status'];
            }
        }

        if (!empty($newProg)) $_SESSION['program'] = $newProg;
        if (!empty($newSec))  $_SESSION['section'] = $newSec;

        // Real-Time Name (Last Name First) & Avatar Sync from MySQL
        if (!empty($liveUser['full_name'])) {
            $_SESSION['name'] = formatLastNameFirst($liveUser['full_name']);
            $_SESSION['raw_name'] = $liveUser['full_name'];
        }
        if (!empty($liveUser['avatar_url'])) {
            $_SESSION['picture'] = $liveUser['avatar_url'];
            $_SESSION['avatar'] = $liveUser['avatar_url'];
        }

    } catch (\Throwable $e) {
        // Fallback: If database is momentarily unreachable during maintenance, preserve active session
    }

    // Refresh last activity timestamp
    $_SESSION['last_activity'] = $now;
    return true;
}

/**
 * Function: destroySession
 *
 * Flushes all session state, invalidates browser session cookies, and destroys the PHP session on disk.
 *
 * @return void
 */
function destroySession(): void {
    $_SESSION = [];

    if (ini_get('session.use_cookies')) {
        $params = session_get_cookie_params();
        setcookie(session_name(), '', time() - 42000,
            $params['path'], $params['domain'],
            $params['secure'], $params['httponly']
        );
    }

    session_destroy();
}

// ─── 3. Role-Based Access Control Guards ───────────────────────────────────────

/**
 * Function: require_login
 *
 * Asserts that the client has an active, validated session.
 * If expired or unauthenticated:
 *   - For JSON/API requests: Emits HTTP 401 with an error payload.
 *   - For HTML web requests: Redirects the browser to `/login.php`.
 *
 * @return void
 */
function require_login(): void {
    if (!isSessionValid()) {
        if (isApiRequest()) {
            http_response_code(401);
            echo json_encode(['success' => false, 'message' => 'Session expired or unauthenticated. Please log in again.']);
            exit();
        }
        header("Location: /login.php");
        exit();
    }
}

/**
 * Function: require_admin
 *
 * Restricts access exclusively to System Administrators and Registrars.
 * Checks BOTH the active session role and authoritative database base_role.
 *
 * Non-admin users (Faculty and Students) attempting to access admin features are
 * logged as a security event and redirected to their dedicated portal.
 *
 * @return void
 */
function require_admin(): void {
    require_login();
    $role = $_SESSION['role'] ?? 'student';
    $baseRole = $_SESSION['base_role'] ?? $role;

    // Both active portal role and baseline account role must belong to admin or registrar
    if (!in_array($role, ['admin', 'registrar']) || !in_array($baseRole, ['admin', 'registrar'])) {
        logSecurityEvent(
            "ACCESS_DENIED: Non-admin attempted access to admin page: " . ($_SESSION['email'] ?? 'unknown'),
            $_SESSION['email'] ?? '',
            'Medium'
        );

        // Determine destination: Faculty goes to teacher portal, Students go to student portal
        $home = (in_array($role, ['teacher', 'faculty']) || in_array($baseRole, ['teacher', 'faculty']))
            ? '/teacher/index.php' 
            : '/student/index.php';

        if (isApiRequest()) {
            http_response_code(403);
            echo json_encode(['success' => false, 'message' => 'Administrator access required.']);
            exit();
        }

        header("Location: $home?denied=admin");
        exit();
    }
}

/**
 * Function: require_teacher
 *
 * Restricts access to Faculty Members, Teachers, and Administrators.
 * Pure students attempting to access teacher areas are redirected to `/student/index.php`.
 *
 * @return void
 */
function require_teacher(): void {
    require_login();
    $role = $_SESSION['role'] ?? 'student';
    $baseRole = $_SESSION['base_role'] ?? $role;
    $isFaculty = in_array($role, ['teacher', 'faculty']) || in_array($baseRole, ['teacher', 'faculty']);
    $isAdmin = in_array($role, ['admin', 'registrar']) || in_array($baseRole, ['admin', 'registrar']);

    if (!$isFaculty && !$isAdmin) {
        logSecurityEvent(
            "ACCESS_DENIED: Student attempted access to faculty page: " . ($_SESSION['email'] ?? 'unknown'),
            $_SESSION['email'] ?? '',
            'Medium'
        );

        if (isApiRequest()) {
            http_response_code(403);
            echo json_encode(['success' => false, 'message' => 'Faculty access required.']);
            exit();
        }

        header("Location: /student/index.php?denied=faculty");
        exit();
    }
}

/**
 * Function: require_student_area
 *
 * Guards student-only endpoints (e.g. personal gradebook, course enrollment).
 * Faculty accounts are prevented from accessing student portals to enforce role separation.
 * Administrators are permitted for testing and oversight, with demo student metadata provided.
 *
 * @return void
 */
function require_student_area(): void {
    require_login();
    $role = $_SESSION['role'] ?? 'student';
    $baseRole = $_SESSION['base_role'] ?? $role;

    $isFaculty = in_array($role, ['teacher', 'faculty']) || in_array($baseRole, ['teacher', 'faculty']);
    $isAdmin = in_array($baseRole, ['admin', 'registrar']) || in_array($role, ['admin', 'registrar']);

    // Block pure faculty from entering student areas
    if ($isFaculty && !$isAdmin) {
        $_SESSION['role'] = 'teacher';
        $_SESSION['active_portal'] = 'faculty';

        logSecurityEvent(
            "ACCESS_DENIED: Faculty account attempted to access student area: " . ($_SESSION['email'] ?? 'unknown'),
            $_SESSION['email'] ?? '',
            'Medium'
        );

        if (isApiRequest()) {
            http_response_code(403);
            echo json_encode(['success' => false, 'message' => 'Student area access denied for faculty accounts.']);
            exit();
        }

        header("Location: /teacher/index.php?denied=student");
        exit();
    }

    // When an administrator tests the student portal, inject demo student metadata if unset
    if ($isAdmin) {
        if (empty($_SESSION['student_number']) || in_array($_SESSION['student_number'], ['N/A', 'ADMIN-001', 'FAC-001', 'GUEST'])) {
            $_SESSION['student_number'] = '2024-00192';
        }
        if (empty($_SESSION['section'])) {
            $_SESSION['section'] = '2A';
        }
        if (empty($_SESSION['program'])) {
            $_SESSION['program'] = 'AIS';
        }
    }
}

// ─── 4. Utility & Helper Functions ─────────────────────────────────────────────

/**
 * Function: isApiRequest
 *
 * Inspects incoming HTTP request headers and URI patterns to determine if the caller
 * expects a JSON response (AJAX/Fetch API request) or a standard HTML document.
 *
 * @return bool True if the request is an API/JSON invocation, false otherwise.
 */
function isApiRequest(): bool {
    $accept = $_SERVER['HTTP_ACCEPT'] ?? '';
    $contentType = $_SERVER['CONTENT_TYPE'] ?? '';
    $isXhr = !empty($_SERVER['HTTP_X_REQUESTED_WITH']) 
        && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';

    return $isXhr 
        || strpos($accept, 'application/json') !== false 
        || strpos($contentType, 'application/json') !== false
        || strpos($_SERVER['REQUEST_URI'] ?? '', '/api/') !== false
        || strpos($_SERVER['SCRIPT_NAME'] ?? '', '/api/') !== false;
}

function getCurrentUser(): array {
    return [
        'id' => $_SESSION['user_id'] ?? null,
        'email' => $_SESSION['email'] ?? null,
        'name' => $_SESSION['name'] ?? 'Guest',
        'role' => $_SESSION['role'] ?? 'student',
        'student_number' => $_SESSION['student_number'] ?? 'N/A'
    ];
}

/**
 * Function: resolveSmartFullName
 *
 * Resolves an authentic, human-readable full name from user record or email.
 * Prevents displaying "Pending Google Sign-In" or raw email handles across the system.
 */
function resolveSmartFullName(string $email, string $existingName = '', string $role = 'student'): string {
    $existingName = trim($existingName);
    if (!empty($existingName) && !str_starts_with($existingName, 'Pending')) {
        return $existingName;
    }

    // 1. Check if a real name exists in the database students or users table
    try {
        $db = getDB();
        $stmt = $db->prepare("SELECT full_name FROM students WHERE LOWER(email) = LOWER(?) AND full_name NOT LIKE '%Pending%' LIMIT 1");
        $stmt->execute([$email]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if (!empty($row['full_name'])) {
            return trim($row['full_name']);
        }

        $uStmt = $db->prepare("SELECT full_name FROM users WHERE LOWER(email) = LOWER(?) AND full_name NOT LIKE '%Pending%' LIMIT 1");
        $uStmt->execute([$email]);
        $uRow = $uStmt->fetch(PDO::FETCH_ASSOC);
        if (!empty($uRow['full_name'])) {
            return trim($uRow['full_name']);
        }
    } catch (\Throwable $e) {}

    // 2. Format name cleanly from email handle
    $handle = explode('@', $email)[0];
    $cleanHandle = preg_replace('/\d+$/', '', $handle);

    if (strtolower($cleanHandle) === 'admin') return 'System Administrator';
    if (strtolower($cleanHandle) === 'faculty') return 'Faculty Member';

    if (str_contains($cleanHandle, '.')) {
        return ucwords(str_replace('.', ' ', $cleanHandle));
    }
    if (str_contains($cleanHandle, '_')) {
        return ucwords(str_replace('_', ' ', $cleanHandle));
    }

    if (!empty($cleanHandle)) {
        return ucfirst($cleanHandle);
    }

    return ($role === 'teacher') ? 'Faculty Member' : (($role === 'admin') ? 'Administrator' : 'Student');
}

if (!function_exists('formatLastNameFirst')) {
    /**
     * Formats any full name into the official Philippine academic standard: LASTNAME, Firstname
     * E.g. "JILO DERRAMAS" -> "DERRAMAS, JILO"
     *      "Crisanta Catipay" -> "CATIPAY, Crisanta"
     *      "Juan dela Cruz" -> "DELA CRUZ, Juan"
     */
    function formatLastNameFirst(?string $fullName): string {
        $fullName = trim($fullName ?? '');
        if (empty($fullName)) return 'NPC User';

        // If it already contains a comma, normalize case on last name
        if (strpos($fullName, ',') !== false) {
            $parts = explode(',', $fullName, 2);
            return strtoupper(trim($parts[0])) . ', ' . trim($parts[1]);
        }

        // Clean honorifics if faculty/admin
        $cleaned = preg_replace('/^(prof\.|dr\.|engr\.|instructor|mr\.|ms\.|mrs\.)\s+/i', '', $fullName);
        $tokens = preg_split('/\s+/', trim($cleaned));

        if (count($tokens) <= 1) {
            return strtoupper($tokens[0]);
        }

        $suffixes = ['jr', 'jr.', 'sr', 'sr.', 'ii', 'iii', 'iv', 'v'];
        $suffix = '';
        $lastToken = end($tokens);
        if (in_array(strtolower($lastToken), $suffixes) && count($tokens) > 2) {
            $suffix = ' ' . array_pop($tokens);
        }

        $cnt = count($tokens);
        $lastLower = strtolower($tokens[$cnt - 1]);
        $prevLower = $cnt >= 2 ? strtolower($tokens[$cnt - 2]) : '';
        $prev2Lower = $cnt >= 3 ? strtolower($tokens[$cnt - 3]) : '';

        if ($cnt >= 3 && in_array($prevLower, ['dela', 'del', 'san'])) {
            $lastName = $tokens[$cnt - 2] . ' ' . $tokens[$cnt - 1] . $suffix;
            $firstName = implode(' ', array_slice($tokens, 0, $cnt - 2));
        } elseif ($cnt >= 4 && $prev2Lower === 'de' && in_array($prevLower, ['la', 'los'])) {
            $lastName = $tokens[$cnt - 3] . ' ' . $tokens[$cnt - 2] . ' ' . $tokens[$cnt - 1] . $suffix;
            $firstName = implode(' ', array_slice($tokens, 0, $cnt - 3));
        } else {
            $lastName = array_pop($tokens) . $suffix;
            $firstName = implode(' ', $tokens);
        }

        return strtoupper($lastName) . ', ' . $firstName;
    }
}
?>
